### ISSUE TITLE
cl-macs on emacs 24.1.1

### ISSUE THREAD

**Issue by goldfeld** [joostkremers/criticmarkup-emacs#1]
Hey, I was running cm-mode fine on my main box with emacs 24.3.1, then when I synced up my init.el to a machine still running 24.1.1 it wouldn't load it up because of cl-macs. Not a biggie, just thought you may want to know.

**Comment by joostkremers** [comment]
Mmm... that's a bit strange. I just checked the source code for Emacs 24.1 and it contains the file `cl-macs.el`, so I don't understand why `require`ing it would be problematic...
