### ISSUE TITLE
add cm-mode to Emacs menu bar

### ISSUE THREAD

**Issue by timmli** [joostkremers/criticmarkup-emacs#10]
I cannot find cm-mode functions there. This would be extremely helpful when trying to convince some of my colleagues (that rather like to click their way through Emacs) to use cm-mode.

**Comment by joostkremers** [comment]
That's certainly doable. I'll let you know when I come up with something.

**Comment by joostkremers** [comment]
Try the latest update. It should include a menu labeled CriticMarkup whenever `cm-mode` is active.

**Comment by joostkremers** [comment]
BTW, it's a very straightforward menu. Feel free to make suggestions for improving it.

**Comment by timmli** [comment]
That should do. Thanks!
