### ISSUE TITLE
(cm-make-markups-writable) doesn't seem to make markups writable

### ISSUE THREAD

**Issue by jkitchin** [joostkremers/criticmarkup-emacs#3]
Awesome package!

The code in that function looks like it should work, but if I run it in a buffer in cm-mode, the markup tags are not writable afterwards. Should they be? Or are they just getting font-locked to read-only again?

**Comment by joostkremers** [comment]
Honestly, I can't say... The markup tags should be writable after running `cm-make-markups-writable` and I have no idea what might cause them not to be.

It's possible that font-lock is doing this, though. I don't fully understand how font-lock works, and it doesn't always work as I expect it to. (IME newly inserted markups aren't always read-only, although they are highlighted correctly.)

When exactly is this issue showing up?

**Comment by jkitchin** [comment]
I think font-lock makes them read-only again. It isn't an issue per se, I just saw the function, tried to use it, and it did not do what I thought it might do based on the name.  I am in the same boat with font-lock ;) I think this is closeable.
