### ISSUE TITLE
Font in screenshot?

### ISSUE THREAD

**Issue by alphapapa** [joostkremers/criticmarkup-emacs#5]
Hi, I was just wondering, what font is used in the screenshot?  It looks nice.  Thanks.

**Comment by joostkremers** [comment]
That's [Linux Libertine](http://www.linuxlibertine.org/). LL is my favourite font, I use it for all my documents and also in those Emacs buffers where I use a variable-pitch face.

**Comment by alphapapa** [comment]
Ah, thanks, I have that one and like it but didn't recognize it.  Will have to give it a try in Emacs.
