### ISSUE TITLE
`font-lock-ensure` not found

### ISSUE THREAD

**Issue by timmli** [joostkremers/criticmarkup-emacs#6]
Under Emacs 24.5.1, I'm getting the following error message when trying to enter `cm-mode`: 

> cm-mode: Symbol's function definition is void: font-lock-ensure

You switched to `font-lock-ensure` recently in commit 5840e8f, which seems to be only supported in Emacs 25. Could you undo this at least for 24.x?

**Comment by joostkremers** [comment]
I pushed a fix for this. Let me know if you run into any trouble.

**Comment by timmli** [comment]
Works fine now. Thanks!
