### ISSUE TITLE
Substitutions don't get applied correctly

### ISSUE THREAD

**Issue by lckarssen** [joostkremers/criticmarkup-emacs#7]
With Emacs 24.5.1, cm-mode from melpa (v. 20160801.108) applying substitutions doesn't seem to work. Instead of replacing the old text with the new text, the old text is replaced with the last letter of the old text. 

For example: `{~~enter~>type~~}` is replaced with `r` after hitting `C-c * i` and choosing `a` (accept). Rejecting the change works as expected. Additions and deletions work as expected.

I checked this also with a clean (`emacs -Q`) session.

**Comment by joostkremers** [comment]
Yes, I've noticed some issues with `cm-mode` as well, but haven't gotten round to fixing them yet. Or figuring out why they happen, for that matter, because when I originally wrote the code, everything worked. I'll look into it.

**Comment by joostkremers** [comment]
Ok, turns out a regexp was wrong. Should be fixed now in commit 81863c2.

**Comment by lckarssen** [comment]
I can confirm that change in commit 81863c2 works. Thanks for the quick fix!
